# syntax = docker/dockerfile:experimental
# DOCKER_BUILDKIT=1 docker build . --target python --tag ai/test:beta --progress=plain
#FROM python:3.10.13-bullseye as python
FROM python:3.10-slim-bullseye as python
RUN --mount=type=cache,target=/var/cache/apt/archives \
    unset ALL_PROXY && unset http_proxy && unset HTTP_PROXY && unset HTTPS_PROXY && unset https_proxy \
    && sed -i 's#http://deb.debian.org#https://mirrors.huaweicloud.com#g' /etc/apt/sources.list && apt update && apt-get install -y libpcre3 libpcre3-dev && apt install -y nginx \
    && apt install -y vim iproute2 gettext gcc
RUN rm -f /etc/localtime \
&& ln -sv /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& echo "Asia/Shanghai" > /etc/timezone


COPY webapi/requirements.txt /tmp

RUN --mount=type=cache,target=/root/.cache/pip \
    unset ALL_PROXY && unset http_proxy && unset HTTP_PROXY && unset HTTPS_PROXY && unset https_proxy  \
    && pip install -r /tmp/requirements.txt -i https://mirrors.cloud.tencent.com/pypi/simple --root-user-action=ignore --disable-pip-version-check



# 设置环境变量,docker-comopse 替换
ENV DOWNLOAD_URL=http://120.133.63.166:5004/attachment/download/ \
    OPENAI_API_BASE=http://120.133.75.252:28002/v1 \
    GPUOS_PLATFORM_URL=http://120.133.83.136:11017/api/v1/chat/completions \
    OUTLINE_MODEL_TYPE=model_3 \
    VECTOR_OPEN=1 \
    GPUOS_PLATFORM=1 \
    LANGCHAIN_RAG=0 \
    FLASK_PORT=5001

#ENV RUN_TYPE=dev \
#    WORD_HOST_WIN=172.22.220.91:5000
ENV RUN_TYPE=prod \
    WORD_HOST_WIN=59.151.19.81:5000 \
    HOMEDIR=/data/ai-reporter/

COPY . /data/ai-reporter/
WORKDIR /data/ai-reporter
RUN rm -f /etc/nginx/sites-available/* && rm -f /etc/nginx/sites-enabled/*
# 赋予脚本执行权限（如果在构建上下文中未设置）
RUN chmod +x /data/ai-reporter/deploy/docker/entrypoint.sh

ENTRYPOINT ["/data/ai-reporter/deploy/docker/entrypoint.sh"]