version: "3.8"
services:
  ai-flask-backend-5004:
    image: ai/test:9004
    container_name: "ai-flask-backend-5004"
    restart: always
    privileged: true
    environment:
#      - LANG=zh_CN.UTF-8
#      - LC_ALL=zh_CN.UTF-8
      - TZ=Asia/Shanghai
      - DOWNLOAD_URL=http://120.133.63.166:5004/attachment/download/
      - LANGCHAIN_RAG=0
      - GPUOS_PLATFORM=1
      - VECTOR_OPEN=1
      - FLASK_PORT=5004
      - GPUOS_PLATFORM_URL=http://120.133.83.136:11017/api/v1/chat/completions
      - OPENAI_API_BASE=http://120.133.75.252:28006/v1
      - WORD_HOST_WIN=59.151.19.81:5000
      - RUN_TYPE=prod
      - OUTLINE_MODEL_TYPE=model_3
      - SCORE=0.65
      - VIEW_URL=http://120.133.63.166:8012/onlinePreview?url=@replace@&officePreviewType=pdf

    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - ../../logs:/data/ai-reporter/logs
      - ../../webapi/app/attachments:/data/ai-reporter/webapi/app/attachments
      - ./9004.json:/data/ai-reporter/config.json
        #ports:
        # - "9000:9000"                        #默认管理端口
    network_mode: host
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5004/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
